services:
  - type: web
    name: skillswap-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # You'll need to set this in Render dashboard
      - key: JWT_SECRET_KEY
        sync: false  # You'll need to set this in Render dashboard
      - key: FRONTEND_ORIGIN
        sync: false  # You'll need to set this to your frontend URL
